Repository Space2Study-UA-1156/BackEnd-01, pull requests merged in 2024-05, with the labels that each got.

#51 Created the separate function to add comments
  src/services/comment.js
Labels: bug, Backend, sprint 1

#53 Total offers field is not recalculated after deleting an offer
  src/models/offer.js
Labels: bug, Backend

#55 Offer's authorAvgRating is not calculating for students
  src/models/review.js
Labels: bug, Backend

#54 User's average rating is not calculating for students
  src/models/review.js
Labels: bug, Backend

#56 Respond with 403 if user is not involed in a cooperation
  src/services/comment.js
Labels: bug, Backend

#61 [Find all categories] query parameter "skip" doesn't work in the proper way
  docs/category/category-schema.yaml
  docs/category/category.yaml
  src/utils/categories/categoriesAggregateOptions.js
Labels: bug, Backend, Categories, sprint 3

#58 Added validation for category model
  src/models/category.js
Labels: Backend, Categories, feature

#62 Feature/60/sp 1 create endpoint for fetching languages
  docs/languages/languages-schema.yaml
  docs/languages/languages.yaml
  src/controllers/languages.js
  src/routes/index.js
  src/routes/languages.js
Labels: Backend, feature, sprint 3

#64 Renamed fields in category model, categoryIcon --> appearance, icon --> path
  docs/category/category-schema.yaml
  docs/category/category.yaml
  docs/review/review.yaml
  src/models/category.js
  src/services/category.js
  src/test/integration/controllers/category.spec.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/offer.spec.js
  src/test/integration/controllers/review.spec.js
Labels: bug, Backend, documentation, Categories

#68 Add involvement check before updating/deleting offers
  src/controllers/offer.js
  src/services/offer.js
Labels: Backend, feature, Find offers

#69 Added offer model validation
  src/models/offer.js
Labels: Backend, feature, Find offers, sprint 5

#70 Added subject model validation
  src/models/subject.js
Labels: Backend, feature, Subjects, sprint 5

#72 fix get all categories response
  src/utils/categories/categoriesAggregateOptions.js
Labels: bug, Backend, Categories, sprint 5

#73 Remove upload service, refactor updateUser service
  src/services/user.js
Labels: Backend

#74 Change path to the email templates
  src/emails/index.js
Labels: bug, Backend

#76 Make subject unique only within a category
  src/models/subject.js
Labels: Backend, sprint 6

#75 Populate category data
  src/services/subject.js
Labels: Backend, Subjects, sprint 6

#79 Implemented Request route
  src/consts/models.js
  src/consts/validation.js
  src/controllers/request.js
  src/models/request.js
  src/routes/index.js
  src/routes/request.js
  src/services/request.js
  src/validation/services/request.js
Labels: Backend, sprint 6

#78 Implemented sorting categories by total offers
  docs/category/category.yaml
  src/utils/categories/categoriesAggregateOptions.js
Labels: Backend, Categories, feature, sprint 6

#80 Implemented file uploading to the Firebase storage
  package-lock.json
  package.json
  src/app.js
  src/configs/config.js
  src/consts/errors.js
  src/initialization/firebaseStorage.js
  src/middlewares/error.js
  src/services/upload.js
  src/services/user.js
Labels: Backend, sprint 6
